package main

import (
	"fmt"
	"os"
)

func main() {
	f, err := os.Create("../md5x16_amd64.s")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	w := func(s string, args ...interface{}) {
		fmt.Fprintf(f, s+"\n", args...)
	}

	w("// Code generated by gen_md5x16; DO NOT EDIT.")
	w("// 16-way MD5 AVX512 — 64 unrolled steps with VPTERNLOGD + VPROLD.")
	w("// Processes 16 parallel blocks using ZMM (512-bit) registers.")
	w("//")
	w("// ⚠️  IMPORTANT — Go Plan 9 asm operand swap for VPTERNLOGD:")
	w("//   Intel manual:  VPTERNLOGD(dst, src1, src2) → n = (dst<<2)|(src1<<1)|src2")
	w("//   Go Plan 9 asm: VPTERNLOGD(src1, src2, dst) → n = (dst<<2)|(src2<<1)|src1  ← SWAPPED!")
	w("//   Same operand-swap behavior as VPANDN in Go asm.")
	w("//   All imm8 values below are computed for the Go-swapped order.")
	w("//   Do NOT use Intel-manual imm8 values — they will produce wrong hashes!")
	w("")
	w("#include \"textflag.h\"")
	w("")
	w("// func md5x16core(x *[16][16]uint32, state *[4][16]uint32)")
	w("TEXT ·md5x16core(SB), NOSPLIT, $0-16")
	w("\tMOVQ x+0(FP), DI")
	w("\tMOVQ state+8(FP), SI")
	w("")
	// Z0-Z3: state (a,b,c,d) — roles rotate per step
	// Z4-Z7: saved initial state
	// Z8: all-ones constant
	w("\tVMOVDQU32 0(SI), Z0")
	w("\tVMOVDQU32 64(SI), Z1")
	w("\tVMOVDQU32 128(SI), Z2")
	w("\tVMOVDQU32 192(SI), Z3")
	w("\tVPTERNLOGD $0xFF, Z8, Z8, Z8") // Z8 = all-ones
	w("")
	w("\t// Save initial state for final add-back")
	w("\tVMOVDQA32 Z0, Z4")
	w("\tVMOVDQA32 Z1, Z5")
	w("\tVMOVDQA32 Z2, Z6")
	w("\tVMOVDQA32 Z3, Z7")
	w("")

	T := [64]uint32{
		0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee,
		0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
		0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be,
		0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
		0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa,
		0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8,
		0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed,
		0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
		0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c,
		0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
		0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05,
		0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
		0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039,
		0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
		0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1,
		0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391,
	}

	shifts := [64]int{}
	gVals := [64]int{}
	for i := 0; i < 64; i++ {
		switch {
		case i < 16:
			gVals[i] = i
			shifts[i] = []int{7, 12, 17, 22}[i%4]
		case i < 32:
			gVals[i] = (5*i + 1) % 16
			shifts[i] = []int{5, 9, 14, 20}[i%4]
		case i < 48:
			gVals[i] = (3*i + 5) % 16
			shifts[i] = []int{4, 11, 16, 23}[i%4]
		default:
			gVals[i] = (7 * i) % 16
			shifts[i] = []int{6, 10, 15, 21}[i%4]
		}
	}

	// VPTERNLOGD immediate values for each round's F function.
	// Computed as: ternary(d, b, c, imm8) where d=dst_initial, b=src1, c=src2
	// Round 1: (b&c) | (~b&d) → imm8=0xB8 (copy d to work reg, then ternlog)
	// Round 2: (b&d) | (c&~d) = c ^ ((b ^ c) & d). We'll use VPTERNLOGD directly.
	// Round 3: b ^ c ^ d → use VPXOR x2
	// Round 4: c ^ (b | ~d) → use VPTERNLOGD

	// Register permutation: same 4-way cycle as AVX2 version
	perm := [4][4]int{
		{0, 1, 2, 3}, // a=Z0, b=Z1, c=Z2, d=Z3
		{3, 0, 1, 2}, // a=Z3, b=Z0, c=Z1, d=Z2
		{2, 3, 0, 1}, // a=Z2, b=Z3, c=Z0, d=Z1
		{1, 2, 3, 0}, // a=Z1, b=Z2, c=Z3, d=Z0
	}

	phys := func(idx int) string { return fmt.Sprintf("Z%d", idx) }

	// Preload X[g0] before the step loop.
	w("\tVMOVDQU32 %d(DI), Z9", gVals[0]*64)
	w("")

	for i := 0; i < 64; i++ {
		g := gVals[i]
		s := shifts[i]
		round := i / 16

		p := perm[i%4]
		rA := phys(p[0])
		rB := phys(p[1])
		rC := phys(p[2])
		rD := phys(p[3])

		w("\t// Step %d: R%d g=%d s=%d T=0x%08x  (a=%s b=%s c=%s d=%s)",
			i, round+1, g, s, T[i], rA, rB, rC, rD)

		// F function via VPTERNLOGD.  X[g] is already in Z9 (preloaded).
		switch round {
		case 0:
			w("\tVMOVDQA32 %s, Z10", rD)
			w("\tVPTERNLOGD $0xD8, %s, %s, Z10", rB, rC)
		case 1:
			w("\tVMOVDQA32 %s, Z10", rD)
			w("\tVPTERNLOGD $0xAC, %s, %s, Z10", rB, rC)
		case 2:
			w("\tVMOVDQA32 %s, Z10", rB)
			w("\tVPXORD  %s, Z10, Z10", rC)
			w("\tVPXORD  %s, Z10, Z10", rD)
		case 3:
			w("\tVMOVDQA32 %s, Z10", rD)
			w("\tVPTERNLOGD $0x63, %s, %s, Z10", rB, rC)
		}

		// ILP: a+X+T in Z11, parallel with F above.
		w("\tVPADDD %s, Z9, Z11", rA)             // a + X  (chain B)
		w("\tVPADDD T16_%d<>+0(SB), Z11, Z11", i) // a + X + T

		// Prefetch next X after Z9 consumed, before merge+rotate chain.
		if i < 63 {
			w("\tVMOVDQU32 %d(DI), Z9", gVals[i+1]*64)
		}

		w("\tVPADDD Z11, Z10, Z10")    // F + (a+X+T)  (merge)
		w("\tVPROLD $%d, Z10, Z10", s) // rotate

		// Write back: ra = rb + result
		w("\tVPADDD %s, Z10, %s", rB, rA)
		w("")
	}

	// After 64 steps, permutation returns to identity: Z0=a, Z1=b, Z2=c, Z3=d
	w("\tVPADDD Z4, Z0, Z0")
	w("\tVPADDD Z5, Z1, Z1")
	w("\tVPADDD Z6, Z2, Z2")
	w("\tVPADDD Z7, Z3, Z3")
	w("")
	w("\tVMOVDQU32 Z0, 0(SI)")
	w("\tVMOVDQU32 Z1, 64(SI)")
	w("\tVMOVDQU32 Z2, 128(SI)")
	w("\tVMOVDQU32 Z3, 192(SI)")
	w("\tVZEROUPPER")
	w("\tRET")
	w("")

	// 16-way inflated T constants: 64 bytes each
	for i, t := range T {
		w("DATA T16_%d<>+0(SB)/4, $0x%08x", i, t)
		for j := 1; j < 16; j++ {
			w("DATA T16_%d<>+%d(SB)/4, $0x%08x", i, j*4, t)
		}
		w("GLOBL T16_%d<>(SB), RODATA|NOPTR, $64", i)
		w("")
	}
}
