package main

import (
	"fmt"
	"os"
)

func main() {
	f, err := os.Create("../md5x8_amd64.s")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	w := func(s string, args ...interface{}) {
		fmt.Fprintf(f, s+"\n", args...)
	}

	w("// Code generated by gen_md5x8; DO NOT EDIT.")
	w("// 8-way MD5 AVX2 — 64 unrolled steps with implicit register rotation.")
	w("// Uses merged T-constant loads (VPADDD from memory) to save instructions.")
	w("")
	w("#include \"textflag.h\"")
	w("")
	w("// func md5x8core(x *[16][8]uint32, state *[4][8]uint32)")
	w("TEXT ·md5x8core(SB), NOSPLIT, $0-16")
	w("\tMOVQ x+0(FP), DI")
	w("\tMOVQ state+8(FP), SI")
	w("")
	// State: Y0=a, Y1=b, Y2=c, Y3=d  (roles rotate per step via permutation)
	// Saved: Y4=sa, Y5=sb, Y6=sc, Y7=sd
	// Const: Y8=allones
	// Work:  Y9,Y10=F temps, Y11=rotl left, Y12=rotl right+accum, Y13=X[g]
	w("\tVMOVDQU 0(SI), Y0")
	w("\tVMOVDQU 32(SI), Y1")
	w("\tVMOVDQU 64(SI), Y2")
	w("\tVMOVDQU 96(SI), Y3")
	w("\tVMOVDQU allones<>+0(SB), Y8")
	w("")
	w("\t// Save initial state for final add-back")
	w("\tVMOVDQA Y0, Y4")
	w("\tVMOVDQA Y1, Y5")
	w("\tVMOVDQA Y2, Y6")
	w("\tVMOVDQA Y3, Y7")
	w("")

	T := [64]uint32{
		0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee,
		0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
		0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be,
		0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
		0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa,
		0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8,
		0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed,
		0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
		0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c,
		0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
		0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05,
		0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
		0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039,
		0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
		0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1,
		0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391,
	}

	shifts := [64]int{}
	gVals := [64]int{}
	for i := 0; i < 64; i++ {
		switch {
		case i < 16:
			gVals[i] = i
			shifts[i] = []int{7, 12, 17, 22}[i%4]
		case i < 32:
			gVals[i] = (5*i + 1) % 16
			shifts[i] = []int{5, 9, 14, 20}[i%4]
		case i < 48:
			gVals[i] = (3*i + 5) % 16
			shifts[i] = []int{4, 11, 16, 23}[i%4]
		default:
			gVals[i] = (7 * i) % 16
			shifts[i] = []int{6, 10, 15, 21}[i%4]
		}
	}

	// Register permutation: logical (a,b,c,d) → physical Y0-Y3
	// ROLES rotate each step, avoiding explicit VMOVDQA shuffles.
	perm := [4][4]int{
		{0, 1, 2, 3}, // i%4==0: a=Y0, b=Y1, c=Y2, d=Y3
		{3, 0, 1, 2}, // i%4==1: a=Y3, b=Y0, c=Y1, d=Y2
		{2, 3, 0, 1}, // i%4==2: a=Y2, b=Y3, c=Y0, d=Y1
		{1, 2, 3, 0}, // i%4==3: a=Y1, b=Y2, c=Y3, d=Y0
	}

	phys := func(idx int) string { return fmt.Sprintf("Y%d", idx) }

	// Preload X[g0] before the step loop (software pipelining:
	// each step loads the NEXT step's X at the end, hiding load latency).
	w("\tVMOVDQU %d(DI), Y13", gVals[0]*32)
	w("")

	// Emit 64 steps with implicit register rotation
	for i := 0; i < 64; i++ {
		g := gVals[i]
		s := shifts[i]
		round := i / 16

		p := perm[i%4]
		rA := phys(p[0])
		rB := phys(p[1])
		rC := phys(p[2])
		rD := phys(p[3])

		w("\t// Step %d: R%d g=%d s=%d T=0x%08x  (a=%s b=%s c=%s d=%s)",
			i, round+1, g, s, T[i], rA, rB, rC, rD)

		// Round function → F in Y12.  X[g] is already in Y13 (preloaded).
		// NOTE: Go Plan 9 VPANDN src1,src2,dst → dst = src1 &^ src2 (not Intel order!)
		switch round {
		case 0: // F = (b&c) | (~b&d) = (b&c) | (d&~b)
			w("\tVPAND  %s, %s, Y9", rB, rC)
			w("\tVPANDN %s, %s, Y10", rD, rB) // Y10 = d &^ b = d & ~b = ~b & d
			w("\tVPOR   Y9, Y10, Y12")
		case 1: // F = (b&d) | (c&~d) = (b&d) | (c&~d)
			w("\tVPAND  %s, %s, Y9", rB, rD)
			w("\tVPANDN %s, %s, Y10", rC, rD) // Y10 = c &^ d = c & ~d
			w("\tVPOR   Y9, Y10, Y12")
		case 2: // F = b ^ c ^ d
			w("\tVPXOR  %s, %s, Y12", rB, rC)
			w("\tVPXOR  %s, Y12, Y12", rD)
		case 3: // F = c ^ (b | ~d) = c ^ (b | ~d)
			w("\tVPANDN %s, %s, Y9", rD, rB) // Y9 = d &^ b = d & ~b
			w("\tVPXOR  Y8, Y9, Y9")         // Y9 = ~(d&~b) = b | ~d
			w("\tVPXOR  %s, Y9, Y12", rC)    // Y12 = c ^ (b | ~d)
		}

		// ILP: compute a+X+T in parallel with F, then combine.
		w("\tVPADDD %s, Y13, Y14", rA)          // a + X  (chain A)
		w("\tVPADDD T_%d<>+0(SB), Y14, Y14", i) // a + X + T

		// Prefetch next X right after Y13 is consumed (before rotation chain).
		// Gives ~4 instructions of slack to hide load latency.
		if i < 63 {
			w("\tVMOVDQU %d(DI), Y13", gVals[i+1]*32)
		}

		w("\tVPADDD Y14, Y12, Y12") // F + (a+X+T)  (merge chains)
		w("\tVPSLLD $%d, Y12, Y11", s)
		w("\tVPSRLD $%d, Y12, Y12", 32-s)
		w("\tVPOR   Y12, Y11, Y12")

		// Write back: ra = rb + rotl_result
		w("\tVPADDD %s, Y12, %s", rB, rA)
		w("")
	}

	// After 64 steps (64%4==0), permutation returns to identity:
	// Y0=a, Y1=b, Y2=c, Y3=d

	// Add back initial state
	w("\tVPADDD Y4, Y0, Y0")
	w("\tVPADDD Y5, Y1, Y1")
	w("\tVPADDD Y6, Y2, Y2")
	w("\tVPADDD Y7, Y3, Y3")
	w("")
	// Store state
	w("\tVMOVDQU Y0, 0(SI)")
	w("\tVMOVDQU Y1, 32(SI)")
	w("\tVMOVDQU Y2, 64(SI)")
	w("\tVMOVDQU Y3, 96(SI)")
	w("\tVZEROUPPER")
	w("\tRET")
	w("")

	// Data tables
	w("DATA allones<>+0(SB)/8,  $0xFFFFFFFFFFFFFFFF")
	w("DATA allones<>+8(SB)/8,  $0xFFFFFFFFFFFFFFFF")
	w("DATA allones<>+16(SB)/8, $0xFFFFFFFFFFFFFFFF")
	w("DATA allones<>+24(SB)/8, $0xFFFFFFFFFFFFFFFF")
	w("GLOBL allones<>(SB), RODATA|NOPTR, $32")
	w("")

	for i, t := range T {
		w("DATA T_%d<>+0(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+4(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+8(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+12(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+16(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+20(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+24(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+28(SB)/4, $0x%08x", i, t)
		w("GLOBL T_%d<>(SB), RODATA|NOPTR, $32", i)
		w("")
	}
}
