package main

import (
	"fmt"
	"os"
	"strconv"
)

func main() {
	nRounds := 64
	if len(os.Args) > 1 {
		if n, err := strconv.Atoi(os.Args[1]); err == nil && n >= 1 && n <= 64 {
			nRounds = n
		}
	}

	f, err := os.Create("../sha256x8_amd64.s")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	w := func(s string, args ...interface{}) {
		fmt.Fprintf(f, s+"\n", args...)
	}

	w("// Code generated by gen_sha256x8; DO NOT EDIT.")
	w("// 8-way SHA-256 AVX2 — %d unrolled rounds with register rotation.", nRounds)
	w("// NOSPLIT $0 frame — all buffers passed via pointer args (like MD5 core).")
	w("")
	w("#include \"textflag.h\"")
	w("")
	w("// func sha256x8coreASM(x *[16][8]uint32, state *[8][8]uint32, wbuf *[16][8]uint32, saved *[8][8]uint32)")
	w("TEXT ·sha256x8coreASM(SB), NOSPLIT, $0-32")
	w("\tMOVQ x+0(FP), DI")
	w("\tMOVQ state+8(FP), SI")
	w("\tMOVQ wbuf+16(FP), R8")
	w("\tMOVQ saved+24(FP), R9")
	w("")

	// Load state: Y0..Y7 = a..h
	for i := 0; i < 8; i++ {
		w("\tVMOVDQU %d(SI), Y%d", i*32, i)
	}
	w("")

	// Save initial state via R9
	for i := 0; i < 8; i++ {
		w("\tVMOVDQU Y%d, %d(R9)", i, i*32)
	}
	w("")

	// K constants
	K := [64]uint32{
		0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5,
		0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
		0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
		0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
		0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc,
		0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
		0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
		0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
		0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
		0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
		0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3,
		0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
		0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5,
		0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
		0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
		0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
	}

	// Register rotation: reg(r, k) = (k - r) & 7
	// k=0(a),1(b),2(c),3(d),4(e),5(f),6(g),7(h)
	logicalOff := map[string]int{"a": 0, "b": 1, "c": 2, "d": 3, "e": 4, "f": 5, "g": 6, "h": 7}
	regName := func(r int, logical string) string {
		return fmt.Sprintf("Y%d", (logicalOff[logical]-r)&7)
	}

	// Generate rounds
	for i := 0; i < nRounds; i++ {
		ra := regName(i, "a")
		rb := regName(i, "b")
		rc := regName(i, "c")
		rd := regName(i, "d")
		re := regName(i, "e")
		rf := regName(i, "f")
		rg := regName(i, "g")
		rh := regName(i, "h")

		if i < 16 {
			w("\t// Round %d (input w[%d]): a=%s b=%s c=%s d=%s e=%s f=%s g=%s h=%s",
				i, i, ra, rb, rc, rd, re, rf, rg, rh)

			// Load w[i] from x (already BE), store to wbuf
			w("\tVMOVDQU %d(DI), Y8", i*32)
			w("\tVMOVDQU Y8, %d(R8)", (i%16)*32)
		} else {
			w("\t// Round %d (schedule w[%d]): a=%s b=%s c=%s d=%s e=%s f=%s g=%s h=%s",
				i, i, ra, rb, rc, rd, re, rf, rg, rh)

			// Message schedule
			w2, w7, w15, w16 := (i-2)&15, (i-7)&15, (i-15)&15, (i-16)&15
			wi := i & 15

			w("\tVMOVDQU %d(R8), Y8", w2*32)
			w("\tVMOVDQU %d(R8), Y9", w7*32)
			w("\tVMOVDQU %d(R8), Y10", w15*32)
			w("\tVMOVDQU %d(R8), Y11", w16*32)

			// σ1(w[i-2]) = ROTR17 ^ ROTR19 ^ SHR10 → Y12
			emitSmallSigma(w, "Y8", "Y12", "Y13", "Y14", 17, 19, 10)

			// σ0(w[i-15]) = ROTR7 ^ ROTR18 ^ SHR3 → Y13
			emitSmallSigma(w, "Y10", "Y13", "Y8", "Y14", 7, 18, 3)

			// w[i] = σ1 + w[i-7] + σ0 + w[i-16] → Y8
			w("\tVPADDD Y9, Y12, Y12")
			w("\tVPADDD Y11, Y12, Y12")
			w("\tVPADDD Y13, Y12, Y8")
			w("\tVMOVDQU Y8, %d(R8)", wi*32)
		}

		// ── Round function (Y8 = w[i]) ──

		// Ch(e,f,g) = (e&f) ^ (~e&g) → Y10
		w("\tVPAND  %s, %s, Y9", re, rf)
		w("\tVPANDN %s, %s, Y10", rg, re)
		w("\tVPXOR  Y9, Y10, Y10")

		// Σ1(e) = ROTR6 ^ ROTR11 ^ ROTR25 → Y11
		emitBigSigma(w, re, "Y11", "Y9", "Y12", 6, 11, 25)

		// Σ0(a) = ROTR2 ^ ROTR13 ^ ROTR22 → Y12
		emitBigSigma(w, ra, "Y12", "Y9", "Y13", 2, 13, 22)

		// Maj(a,b,c) = (a&b)^(a&c)^(b&c) → Y13
		w("\tVPAND  %s, %s, Y9", ra, rb)
		w("\tVPAND  %s, %s, Y13", ra, rc)
		w("\tVPXOR  Y9, Y13, Y13")
		w("\tVPAND  %s, %s, Y9", rb, rc)
		w("\tVPXOR  Y9, Y13, Y13")

		// T1 = h + Σ1 + Ch + K + w → Y11
		w("\tVPADDD %s, Y11, Y11", rh)
		w("\tVPADDD Y10, Y11, Y11")
		w("\tVPADDD K_%d<>+0(SB), Y11, Y11", i)
		w("\tVPADDD Y8, Y11, Y11")

		// T2 = Σ0 + Maj → Y12
		w("\tVPADDD Y13, Y12, Y12")

		// new_a = T1+T2 → old_h's physical reg
		// new_e = d+T1  → old_d's physical reg
		newA := regName(i+1, "a")
		newE := regName(i+1, "e")
		w("\tVPADDD Y11, Y12, Y9")
		w("\tVPADDD %s, Y11, Y10", rd)
		w("\tVMOVDQA Y9, %s", newA)
		w("\tVMOVDQA Y10, %s", newE)
		w("")
	}

	// Add back initial state — use Y8-Y15 as temp to avoid source/dest overlap
	w("\t// Add back initial state (via temps to avoid register overlap)")
	w("\tVPADDD %d(R9), %s, Y8", 0*32, regName(nRounds, "a"))
	w("\tVPADDD %d(R9), %s, Y9", 1*32, regName(nRounds, "b"))
	w("\tVPADDD %d(R9), %s, Y10", 2*32, regName(nRounds, "c"))
	w("\tVPADDD %d(R9), %s, Y11", 3*32, regName(nRounds, "d"))
	w("\tVPADDD %d(R9), %s, Y12", 4*32, regName(nRounds, "e"))
	w("\tVPADDD %d(R9), %s, Y13", 5*32, regName(nRounds, "f"))
	w("\tVPADDD %d(R9), %s, Y14", 6*32, regName(nRounds, "g"))
	w("\tVPADDD %d(R9), %s, Y15", 7*32, regName(nRounds, "h"))
	w("")
	w("\t// Move temps to store-order registers")
	w("\tVMOVDQA Y8, Y7")
	w("\tVMOVDQA Y9, Y0")
	w("\tVMOVDQA Y10, Y1")
	w("\tVMOVDQA Y11, Y2")
	w("\tVMOVDQA Y12, Y3")
	w("\tVMOVDQA Y13, Y4")
	w("\tVMOVDQA Y14, Y5")
	w("\tVMOVDQA Y15, Y6")
	w("")

	// Store state
	w("\tVMOVDQU Y7, 0(SI)")
	w("\tVMOVDQU Y0, 32(SI)")
	w("\tVMOVDQU Y1, 64(SI)")
	w("\tVMOVDQU Y2, 96(SI)")
	w("\tVMOVDQU Y3, 128(SI)")
	w("\tVMOVDQU Y4, 160(SI)")
	w("\tVMOVDQU Y5, 192(SI)")
	w("\tVMOVDQU Y6, 224(SI)")
	w("")
	w("\tVZEROUPPER")
	w("\tRET")
	w("")

	// DATA: K constants (8x inflated)
	for i, k := range K {
		w("DATA K_%d<>+0(SB)/4, $0x%08x", i, k)
		for j := 1; j < 8; j++ {
			w("DATA K_%d<>+%d(SB)/4, $0x%08x", i, j*4, k)
		}
		w("GLOBL K_%d<>(SB), RODATA|NOPTR, $32", i)
		w("")
	}
}

func emitBigSigma(w func(string, ...interface{}), src, dst, tmp1, tmp2 string, r1, r2, r3 int) {
	w("\tVPSRLD $%d, %s, %s", r1, src, tmp1)
	w("\tVPSLLD $%d, %s, %s", 32-r1, src, tmp2)
	w("\tVPOR   %s, %s, %s", tmp2, tmp1, dst)
	w("\tVPSRLD $%d, %s, %s", r2, src, tmp1)
	w("\tVPSLLD $%d, %s, %s", 32-r2, src, tmp2)
	w("\tVPOR   %s, %s, %s", tmp2, tmp1, tmp1)
	w("\tVPXOR  %s, %s, %s", tmp1, dst, dst)
	w("\tVPSRLD $%d, %s, %s", r3, src, tmp1)
	w("\tVPSLLD $%d, %s, %s", 32-r3, src, tmp2)
	w("\tVPOR   %s, %s, %s", tmp2, tmp1, tmp1)
	w("\tVPXOR  %s, %s, %s", tmp1, dst, dst)
}

func emitSmallSigma(w func(string, ...interface{}), src, dst, tmp1, tmp2 string, r1, r2, s3 int) {
	w("\tVPSRLD $%d, %s, %s", r1, src, tmp1)
	w("\tVPSLLD $%d, %s, %s", 32-r1, src, tmp2)
	w("\tVPOR   %s, %s, %s", tmp2, tmp1, dst)
	w("\tVPSRLD $%d, %s, %s", r2, src, tmp1)
	w("\tVPSLLD $%d, %s, %s", 32-r2, src, tmp2)
	w("\tVPOR   %s, %s, %s", tmp2, tmp1, tmp1)
	w("\tVPXOR  %s, %s, %s", tmp1, dst, dst)
	w("\tVPSRLD $%d, %s, %s", s3, src, tmp1)
	w("\tVPXOR  %s, %s, %s", tmp1, dst, dst)
}
